// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rpg_Restapi.Data;

namespace Rpg_Restapi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201228105931_FixRelationWeaponCharacter")]
    partial class FixRelationWeaponCharacter
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Rpg_Restapi.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Class")
                        .HasColumnType("integer");

                    b.Property<int>("Defeats")
                        .HasColumnType("integer");

                    b.Property<int>("Defense")
                        .HasColumnType("integer");

                    b.Property<int>("Fights")
                        .HasColumnType("integer");

                    b.Property<int>("HitPoints")
                        .HasColumnType("integer");

                    b.Property<int>("Intelligence")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Strength")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Victories")
                        .HasColumnType("integer");

                    b.Property<Guid>("WeaponId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WeaponId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Class = 1,
                            Defeats = 0,
                            Defense = 10,
                            Fights = 0,
                            HitPoints = 100,
                            Intelligence = 10,
                            Name = "Frodo",
                            Strength = 15,
                            UserId = 1,
                            Victories = 0,
                            WeaponId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = 2,
                            Class = 2,
                            Defeats = 0,
                            Defense = 5,
                            Fights = 0,
                            HitPoints = 100,
                            Intelligence = 20,
                            Name = "Raistlin",
                            Strength = 5,
                            UserId = 2,
                            Victories = 0,
                            WeaponId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Rpg_Restapi.Models.CharacterSkill", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.HasKey("CharacterId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("CharacterSkills");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            SkillId = 2
                        },
                        new
                        {
                            CharacterId = 2,
                            SkillId = 1
                        },
                        new
                        {
                            CharacterId = 2,
                            SkillId = 3
                        });
                });

            modelBuilder.Entity("Rpg_Restapi.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Damage = 30,
                            Name = "Fireball"
                        },
                        new
                        {
                            Id = 2,
                            Damage = 20,
                            Name = "Frenzy"
                        },
                        new
                        {
                            Id = 3,
                            Damage = 50,
                            Name = "Blizzard"
                        });
                });

            modelBuilder.Entity("Rpg_Restapi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Player");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = new byte[] { 150, 178, 103, 11, 75, 81, 100, 202, 117, 168, 147, 157, 131, 177, 227, 35, 185, 126, 199, 81, 70, 205, 85, 247, 13, 69, 100, 233, 214, 108, 3, 70, 13, 150, 42, 6, 212, 1, 184, 125, 28, 82, 238, 233, 18, 213, 124, 72, 255, 4, 106, 125, 216, 218, 168, 221, 180, 193, 5, 0, 135, 194, 140, 15 },
                            PasswordSalt = new byte[] { 169, 47, 248, 21, 228, 147, 219, 53, 104, 191, 15, 141, 146, 119, 205, 246, 240, 3, 224, 243, 180, 188, 2, 177, 179, 139, 121, 151, 240, 204, 18, 71, 93, 17, 222, 33, 91, 138, 128, 198, 159, 78, 122, 11, 255, 235, 69, 202, 75, 87, 10, 135, 8, 146, 207, 242, 156, 62, 45, 48, 229, 139, 250, 116, 113, 39, 249, 214, 155, 72, 13, 90, 118, 77, 21, 97, 134, 2, 211, 85, 4, 178, 67, 29, 179, 144, 227, 3, 89, 152, 146, 203, 63, 213, 253, 147, 134, 70, 196, 180, 207, 220, 242, 91, 77, 10, 68, 109, 51, 193, 227, 176, 40, 128, 234, 237, 31, 207, 142, 169, 38, 18, 231, 99, 213, 73, 10, 121 },
                            Role = "Player",
                            Username = "user1"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = new byte[] { 150, 178, 103, 11, 75, 81, 100, 202, 117, 168, 147, 157, 131, 177, 227, 35, 185, 126, 199, 81, 70, 205, 85, 247, 13, 69, 100, 233, 214, 108, 3, 70, 13, 150, 42, 6, 212, 1, 184, 125, 28, 82, 238, 233, 18, 213, 124, 72, 255, 4, 106, 125, 216, 218, 168, 221, 180, 193, 5, 0, 135, 194, 140, 15 },
                            PasswordSalt = new byte[] { 169, 47, 248, 21, 228, 147, 219, 53, 104, 191, 15, 141, 146, 119, 205, 246, 240, 3, 224, 243, 180, 188, 2, 177, 179, 139, 121, 151, 240, 204, 18, 71, 93, 17, 222, 33, 91, 138, 128, 198, 159, 78, 122, 11, 255, 235, 69, 202, 75, 87, 10, 135, 8, 146, 207, 242, 156, 62, 45, 48, 229, 139, 250, 116, 113, 39, 249, 214, 155, 72, 13, 90, 118, 77, 21, 97, 134, 2, 211, 85, 4, 178, 67, 29, 179, 144, 227, 3, 89, 152, 146, 203, 63, 213, 253, 147, 134, 70, 196, 180, 207, 220, 242, 91, 77, 10, 68, 109, 51, 193, 227, 176, 40, 128, 234, 237, 31, 207, 142, 169, 38, 18, 231, 99, 213, 73, 10, 121 },
                            Role = "Player",
                            Username = "user2"
                        });
                });

            modelBuilder.Entity("Rpg_Restapi.Models.Weapon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Weapons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cbc9cca1-982c-4c49-9847-7e19cf64610d"),
                            Damage = 20,
                            Name = "The Master Sword"
                        },
                        new
                        {
                            Id = new Guid("6f5a9354-b679-4c56-b4e5-fc43ea24bc9e"),
                            Damage = 5,
                            Name = "Crystal Wand"
                        });
                });

            modelBuilder.Entity("Rpg_Restapi.Models.Character", b =>
                {
                    b.HasOne("Rpg_Restapi.Models.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rpg_Restapi.Models.Weapon", "Weapon")
                        .WithMany()
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rpg_Restapi.Models.CharacterSkill", b =>
                {
                    b.HasOne("Rpg_Restapi.Models.Character", "Character")
                        .WithMany("CharacterSkills")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rpg_Restapi.Models.Skill", "Skill")
                        .WithMany("CharacterSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
